#!/usr/bin/env node
// Generates every token artifact from tokens/netix.tokens.json. `--check` fails on drift.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

const BANNER = 'GENERATED by scripts/gen-tokens.mjs from tokens/netix.tokens.json — do not edit.'
const MODES = ['light', 'dark']
const IDENT = /^[A-Za-z_$][\w$]*$/

export const loadTokens = (root = ROOT) =>
  JSON.parse(readFileSync(join(root, 'tokens/netix.tokens.json'), 'utf8'))

const pick = (value, mode) => (typeof value === 'string' ? value : value[mode])

const varies = (value) => typeof value !== 'string' && value.light !== value.dark

const decl = (name, value) => `  --${name}: ${value};`

const block = (selector, body) => `${selector} {\n${body.join('\n')}\n}`

const indent = (text) =>
  text
    .split('\n')
    .map((line) => (line ? `  ${line}` : line))
    .join('\n')

/** Ordered [name, value] pairs for one mode: every group, then the radius scale. */
export function flatten(src, mode) {
  const out = []
  for (const group of src.groups)
    for (const [name, value] of Object.entries(group.tokens)) out.push([name, pick(value, mode)])
  for (const [name, value] of Object.entries(src.radiusScale)) out.push([name, value])
  return out
}

/** Substitutes var(--x) references until every value is a literal; cycles resolve to themselves. */
export function resolve(pairs) {
  const map = Object.fromEntries(pairs)
  const cache = {}
  const expand = (name, stack) => {
    if (name in cache) return cache[name]
    if (stack.includes(name)) return map[name]
    const value = map[name].replace(/var\(--([\w-]+)\)/g, (whole, ref) =>
      ref in map ? expand(ref, [...stack, name]) : whole,
    )
    cache[name] = value
    return value
  }
  return Object.fromEntries(Object.keys(map).map((name) => [name, expand(name, [])]))
}

const fontFaces = (src) =>
  src.font.faces
    .map((face) =>
      [
        '@font-face {',
        `  font-family: '${src.font.family}';`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        '  font-display: swap;',
        `  src: url('${src.font.dir}/${face.file}') format('woff2');`,
        '}',
      ].join('\n'),
    )
    .join('\n\n')

/** Declarations for one mode; dark carries only the tokens that actually change. */
const modeBody = (src, mode, withRadius = false) => {
  const lines = []
  for (const group of src.groups) {
    const tokens = Object.entries(group.tokens).filter(
      ([, value]) => mode === 'light' || varies(value),
    )
    if (!tokens.length) continue
    lines.push(`  /* ${group.name} */`)
    for (const [name, value] of tokens) lines.push(decl(name, pick(value, mode)))
    lines.push('')
  }
  if (withRadius)
    for (const [name, value] of Object.entries(src.radiusScale)) lines.push(decl(name, value))
  else lines.pop()
  return lines
}

const densityBlocks = (src) =>
  Object.entries(src.density).map(([name, tokens]) =>
    block(
      `[data-density='${name}']`,
      Object.entries(tokens).map(([token, value]) => decl(token, value)),
    ),
  )

const REDUCED_MOTION = `@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.001ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.001ms !important;
  }
}`

const keyframesCss = (src) =>
  Object.entries(src.tailwind.keyframes)
    .map(([name, stops]) => {
      const body = Object.entries(stops).map(([stop, rules]) =>
        indent(
          block(
            stop,
            Object.entries(rules).map(([prop, value]) => `  ${prop}: ${value};`),
          ),
        ),
      )
      return block(`@keyframes ${name}`, body)
    })
    .join('\n\n')

/** The @custom-variant + @theme contract Tailwind needs at compile time. */
const themeBlocks = (src) => {
  const theme = [
    '  --font-sans: var(--font-sans);',
    '  --font-mono: var(--font-mono);',
    '  --font-arabic: var(--font-arabic);',
    ...Object.entries(src.tailwind.colors).map(
      ([key, name]) => `  --color-${key}: var(--${name});`,
    ),
    ...Object.entries(src.tailwind.boxShadow).map(
      ([key, name]) => `  --shadow-${key}: var(--${name});`,
    ),
    ...Object.entries(src.tailwind.animation).map(
      ([key, value]) => `  --animate-${key}: ${value};`,
    ),
    '',
    indent(keyframesCss(src)),
  ]
  return [
    '@custom-variant dark (&:is(.dark *));',
    '',
    block('@theme inline', theme),
    '',
    '/* Non-inline @theme: declares the radius vars and wires rounded-* to them. */',
    block(
      '@theme',
      Object.entries(src.radiusScale).map(([name, value]) => decl(name, value)),
    ),
  ]
}

/** Compile-time-only variant for styles-notokens.css: no runtime CSS, no fonts. */
export function buildThemeOnlyCss(src) {
  return [`/* ${BANNER} */`, '', ...themeBlocks(src), ''].join('\n')
}

export function buildTokensCss(src) {
  const [customVariant, , ...themeRest] = themeBlocks(src)
  return [
    `/* ${BANNER} */`,
    '',
    customVariant,
    '',
    fontFaces(src),
    '',
    block(':root', modeBody(src, 'light')),
    '',
    block('.dark', modeBody(src, 'dark')),
    '',
    ...densityBlocks(src),
    '',
    ...themeRest,
    '',
    block('@layer base', [
      indent(
        block('body', [
          '  background-color: var(--background);',
          '  color: var(--foreground);',
          '  font-family: var(--font-sans);',
          '  -webkit-font-smoothing: antialiased;',
          '  -moz-osx-font-smoothing: grayscale;',
        ]),
      ),
      '',
      indent(block('*:focus-visible', ['  outline: none;', '  box-shadow: var(--focus-ring);'])),
    ]),
    '',
    REDUCED_MOTION,
    '',
  ].join('\n')
}

export function buildVarsCss(src) {
  const dark = modeBody(src, 'dark')
  return [
    `/* ${BANNER} */`,
    '/* Plain custom properties for apps without Tailwind: OS preference first, [data-theme] wins. */',
    '',
    fontFaces(src),
    '',
    block(":root,\n[data-theme='light']", [
      '  color-scheme: light;',
      '',
      ...modeBody(src, 'light', true),
    ]),
    '',
    '@media (prefers-color-scheme: dark) {',
    indent(
      block(":root:not([data-theme='light']):not(.light)", ['  color-scheme: dark;', '', ...dark]),
    ),
    '}',
    '',
    block(".dark,\n[data-theme='dark']", ['  color-scheme: dark;', '', ...dark]),
    '',
    ...densityBlocks(src),
    '',
    REDUCED_MOTION,
    '',
  ].join('\n')
}

/** Serializes a plain JSON value as a prettier-shaped JS literal. */
const js = (value, pad = '  ') => {
  if (typeof value !== 'object') return `'${value}'`
  const inner = `${pad}  `
  const entries = Object.entries(value).map(
    ([key, child]) => `${inner}${IDENT.test(key) ? key : `'${key}'`}: ${js(child, inner)},`,
  )
  return `{\n${entries.join('\n')}\n${pad}}`
}

export function buildPresetCjs(src) {
  const { colors, boxShadow, ...rest } = src.tailwind
  const colorLines = Object.entries(colors)
    .map(([key, name]) => `  ${IDENT.test(key) ? key : `'${key}'`}: withAlpha('${name}'),`)
    .join('\n')
  const shadows = Object.fromEntries(
    Object.entries(boxShadow).map(([key, name]) => [key, `var(--${name})`]),
  )
  return `// ${BANNER}
// Tailwind v3 compatibility preset. withAlpha keeps opacity modifiers (bg-card/50) working for
// custom properties that hold full colour values — v3 drops the modifier otherwise.
const withAlpha = (name) =>
  \`color-mix(in srgb, var(--\${name}) calc(<alpha-value> * 100%), transparent)\`

const colors = {
${colorLines}
}

module.exports = {
  darkMode: ['class'],
  theme: {
    extend: {
      colors,
      fontFamily: ${js(rest.fontFamily, '      ')},
      borderRadius: ${js(rest.borderRadius, '      ')},
      borderWidth: ${js(rest.borderWidth, '      ')},
      boxShadow: ${js(shadows, '      ')},
      keyframes: ${js(rest.keyframes, '      ')},
      animation: ${js(rest.animation, '      ')},
    },
  },
}
`
}

/** Prettier keeps single quotes unless the value itself contains one. */
const tsString = (value) => (value.includes("'") ? JSON.stringify(value) : `'${value}'`)

export function buildTokensTs(src) {
  const modes = MODES.map((mode) => {
    const entries = Object.entries(resolve(flatten(src, mode))).map(([name, value]) => {
      const key = IDENT.test(name) ? name : `'${name}'`
      const line = `    ${key}: ${tsString(value)},`
      // Prettier moves an over-wide value onto its own line rather than leaving it hanging.
      return line.length > 100 ? `    ${key}:\n      ${tsString(value)},` : line
    })
    return `  ${mode}: {\n${entries.join('\n')}\n  },`
  })
  return `// ${BANNER}\n\nexport const tokens = {\n${modes.join('\n')}\n} as const\n`
}

/** Single-file apps inline this instead of copying theme-init.js into public/. */
export function buildThemeInitSnippet(root = ROOT) {
  const source = readFileSync(join(root, 'src/tokens/theme-init.js'), 'utf8')
  const escaped = source.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
  return `// ${BANNER}\n\nexport const themeInitSnippet = \`${escaped}\`\n`
}

/** Every generated text artifact, keyed by repo-relative path. */
export function buildAll(src, root = ROOT) {
  return {
    'dist/tokens/tokens.css': buildTokensCss(src),
    'dist/tokens/theme-only.css': buildThemeOnlyCss(src),
    'dist/tokens/vars.css': buildVarsCss(src),
    'dist/tokens/preset.cjs': buildPresetCjs(src),
    'dist/tokens/theme-init.js': readFileSync(join(root, 'src/tokens/theme-init.js'), 'utf8'),
    'src/tokens/tokens.ts': buildTokensTs(src),
    'src/tokens/theme-init-snippet.ts': buildThemeInitSnippet(root),
  }
}

const fontCopies = (src) =>
  [...src.font.faces.map((face) => face.file), 'OFL.txt'].map((file) => [
    `tokens/fonts/${file}`,
    `dist/fonts/${file}`,
  ])

const read = (path) => {
  try {
    return readFileSync(path)
  } catch {
    return null
  }
}

export function write(root, src) {
  for (const [path, content] of Object.entries(buildAll(src, root))) {
    mkdirSync(dirname(join(root, path)), { recursive: true })
    writeFileSync(join(root, path), content)
  }
  for (const [from, to] of fontCopies(src)) {
    mkdirSync(dirname(join(root, to)), { recursive: true })
    copyFileSync(join(root, from), join(root, to))
  }
}

/** Repo-relative paths whose committed contents differ from a fresh generation. */
export function check(root, src) {
  const drift = []
  for (const [path, content] of Object.entries(buildAll(src, root)))
    if (read(join(root, path))?.toString('utf8') !== content) drift.push(path)
  for (const [from, to] of fontCopies(src))
    if (!read(join(root, from))?.equals(read(join(root, to)) ?? Buffer.alloc(0))) drift.push(to)
  return drift
}

const stdout = (message) => process.stdout.write(`${message}\n`)

export function main(argv = [], root = ROOT, log = stdout) {
  const src = loadTokens(root)
  if (!argv.includes('--check')) {
    write(root, src)
    log('tokens: generated')
    return 0
  }
  const drift = check(root, src)
  if (!drift.length) {
    log('tokens: up to date')
    return 0
  }
  log(`tokens: drift in ${drift.join(', ')} — run \`pnpm gen:tokens\``)
  return 1
}

if (process.argv[1] === fileURLToPath(import.meta.url)) process.exit(main(process.argv.slice(2)))
