// GENERATED by scripts/gen-tokens.mjs from tokens/netix.tokens.json — do not edit.

export const themeInitSnippet = `// Applies the stored theme before first paint; keep in sync with ThemeProvider.
;(function () {
  try {
    var root = document.documentElement
    var key = root.dataset.themeKey || 'netix-theme'
    var stored = localStorage.getItem(key) || root.dataset.defaultTheme || 'system'
    var dark =
      stored === 'dark' ||
      (stored === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches)
    var resolved = dark ? 'dark' : 'light'
    root.classList.add(resolved)
    root.style.colorScheme = resolved
  } catch {
    // localStorage/matchMedia unavailable — fall back to the light default
  }
})()
`
